name:                coinflow
version:             0.1.0.0
github:              "t4ccer/coinflow"
license:             GPL-3-or-later
author:              "t4ccer"
maintainer:          "t4ccre@gmail.com"
copyright:           "t4ccer"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/t4ccer/coinflow#readme>

dependencies:
- base >= 4.10.0 && < 5

library:
  source-dirs: src

executables:
  list-concat-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wno-unused-do-bind
    - -Wpartial-fields
    - -Wincomplete-uni-patterns
    dependencies:
    - coinflow

